# Generated by Django 2.1.7 on 2019-10-19 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classwork_app', '0002_contactmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=7),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='referer',
            field=models.CharField(blank=True, choices=[('facebook', 'Faceboo'), ('instagram', 'Instagram'), ('nairaland', 'Nairaland'), ('twitter', 'Twitter'), ('', 'Please Choose')], default='', max_length=10),
        ),
    ]
