# Generated by Django 2.1.7 on 2019-10-19 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classwork_app', '0003_auto_20191019_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='subject',
            field=models.CharField(max_length=20, null=True, verbose_name='Subject'),
        ),
    ]
